import { StyleSheet } from "react-native";

export const CommonStyle = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    backgroundColor: "white",
  },
  logo: {
    width: 150,
    height: 105,
    marginBottom: 40,
    alignSelf: "center",
    marginLeft: 10,
    marginTop: 40,
  },
  loginText: {
    fontSize: 40,
    fontWeight: "bold",
    alignSelf: "flex-start",
    marginBottom: 20,
    fontFamily: "Times New Roman",
    paddingHorizontal: 15,
    color: "#1F2E33",
  },
  input: {
    width: "90%",
    height: 60,
    borderColor: "#CCCCCC",
    borderWidth: 1,
    borderRadius: 30,
    marginBottom: 10,
    paddingHorizontal: 30,
  },
  focusedInput: {
    borderColor: "#4b968f",
  },
  forgotPassword: {
    color: "blue",
    marginBottom: 10,
  },
  loginButton: {
    width: "90%",
    height: 40,
    backgroundColor: "#4b968f",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    color: "white",
    borderRadius: 30,
  },
  loginButtonText: {
    color: "white",
    fontFamily: "Times New Roman",
    fontWeight: "bold",
  },
  googleButton: {
    width: 130,
    height: 60,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 30,
    borderColor: "#CCCCCC",
    justifyContent: "center",
    padding: 5,
    marginBottom: 10,
    color: "blue",
  },
  microsoftButton: {
    width: 130,
    height: 60,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    justifyContent: "center",
    borderRadius: 30,
    borderColor: "#CCCCCC",
    padding: 8,
    marginBottom: 10,
    color: "blue",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
    marginBottom: 20,
  },
  buttonIcon: {
    width: 20,
    height: 20,
    marginRight: 10,
  },
  buttonText: {
    color: "#4b968f",
    fontWeight: "bold",
  },
  divider: {
    width: "90%",
    height: 1,
    backgroundColor: "#CCCCCC",
    marginVertical: 20,
  },
  guestSection: {
    marginTop: 20,
    marginBottom: 40,
    alignItems: "center",
  },
  firstText: {
    fontSize: 20,
    alignSelf: "flex-start",
    color: "#1F2E33",
    fontFamily: "Times New Roman",
    fontWeight: "bold",
    padding: 10,
    marginLeft: 10,
  },
  guestText: {
    textAlign: "center",
    marginBottom: 10,
    marginLeft: 10,
  },
  createAccountButton: {
    backgroundColor: "white",
    borderRadius: 25,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderWidth: 1,
    marginTop: 10,
    borderColor: "#4b968f",
  },
  createAccountButtonText: {
    color: "#4b968f",
    fontWeight: "bold",

    justifyContent: "center",
  },
  arrowButton: {
    backgroundColor: "#ccc",
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  arrowButtonText: {
    color: "white",
    fontWeight: "bold",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "white",
  },
  scrollViewContent: {
    flexGrow: 1,
    backgroundColor: "#f8f8f8",
  },
});
